spring:
  datasource:
    url: jdbc:sqlserver://spring-db-server-23.database.windows.net:1433;database=spring-db-1;encrypt=true;trustServerCertificate=false;hostNameInCertificate=*.database.windows.net;loginTimeout=30;
    username: azuredbuser
    password: Lordshiva$23
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
      dialect : org.hibernate.dialect.SQLServer2012Dialect

server:
  port: 9191


